server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springnote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: ${local.datasource.password}
#    password: mysql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  resources:
    static-locations: classpath:/templates/ # 可以直接访问目录下的html
  redis:
    host: www.knifebrink.com # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: redis456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 47.107.161.11:9300 # es的连接地址及端口号
#      cluster-name: elasticsearch # es集群的名称
#    mongodb:
#      host: 0.0.0.1 # mongodb的连接地址
#      port: 27017 # mongodb的连接端口号
#      database: mall-port # mongodb的连接的数据库
#      password:
#      username:
  rabbitmq:
    host: www.knifebrink.com # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: 0 # rabbitmq的用户名
    password: 0 # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  profiles:
    include: password

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/spring/test/chapter6/*.xml
  configuration:
    cache-enabled: false
    localCacheScope: statement

management:
  endpoints:
    web:
      exposure:
        include : "*"

logging:
  level:
#    root: info
    com.spring.test.chapter6: debug
    com.spring.test.chapter6.chapter6: info

fch:
  ccc: aaa
  bbb: aaa